// Code generated by mockery v2.43.0. DO NOT EDIT.

package sophrosyne

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckService is an autogenerated mock type for the HealthCheckService type
type MockHealthCheckService struct {
	mock.Mock
}

type MockHealthCheckService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckService) EXPECT() *MockHealthCheckService_Expecter {
	return &MockHealthCheckService_Expecter{mock: &_m.Mock}
}

// AuthenticatedHealthcheck provides a mock function with given fields: ctx
func (_m *MockHealthCheckService) AuthenticatedHealthcheck(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticatedHealthcheck")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHealthCheckService_AuthenticatedHealthcheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticatedHealthcheck'
type MockHealthCheckService_AuthenticatedHealthcheck_Call struct {
	*mock.Call
}

// AuthenticatedHealthcheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthCheckService_Expecter) AuthenticatedHealthcheck(ctx interface{}) *MockHealthCheckService_AuthenticatedHealthcheck_Call {
	return &MockHealthCheckService_AuthenticatedHealthcheck_Call{Call: _e.mock.On("AuthenticatedHealthcheck", ctx)}
}

func (_c *MockHealthCheckService_AuthenticatedHealthcheck_Call) Run(run func(ctx context.Context)) *MockHealthCheckService_AuthenticatedHealthcheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthCheckService_AuthenticatedHealthcheck_Call) Return(_a0 []byte, _a1 error) *MockHealthCheckService_AuthenticatedHealthcheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHealthCheckService_AuthenticatedHealthcheck_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockHealthCheckService_AuthenticatedHealthcheck_Call {
	_c.Call.Return(run)
	return _c
}

// UnauthenticatedHealthcheck provides a mock function with given fields: ctx
func (_m *MockHealthCheckService) UnauthenticatedHealthcheck(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UnauthenticatedHealthcheck")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHealthCheckService_UnauthenticatedHealthcheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnauthenticatedHealthcheck'
type MockHealthCheckService_UnauthenticatedHealthcheck_Call struct {
	*mock.Call
}

// UnauthenticatedHealthcheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthCheckService_Expecter) UnauthenticatedHealthcheck(ctx interface{}) *MockHealthCheckService_UnauthenticatedHealthcheck_Call {
	return &MockHealthCheckService_UnauthenticatedHealthcheck_Call{Call: _e.mock.On("UnauthenticatedHealthcheck", ctx)}
}

func (_c *MockHealthCheckService_UnauthenticatedHealthcheck_Call) Run(run func(ctx context.Context)) *MockHealthCheckService_UnauthenticatedHealthcheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthCheckService_UnauthenticatedHealthcheck_Call) Return(_a0 bool) *MockHealthCheckService_UnauthenticatedHealthcheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckService_UnauthenticatedHealthcheck_Call) RunAndReturn(run func(context.Context) bool) *MockHealthCheckService_UnauthenticatedHealthcheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckService creates a new instance of MockHealthCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckService {
	mock := &MockHealthCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
