// Code generated by mockery v2.43.1. DO NOT EDIT.

package sophrosyne

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMetricService is an autogenerated mock type for the MetricService type
type MockMetricService struct {
	mock.Mock
}

type MockMetricService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricService) EXPECT() *MockMetricService_Expecter {
	return &MockMetricService_Expecter{mock: &_m.Mock}
}

// RecordPanic provides a mock function with given fields: ctx
func (_m *MockMetricService) RecordPanic(ctx context.Context) {
	_m.Called(ctx)
}

// MockMetricService_RecordPanic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPanic'
type MockMetricService_RecordPanic_Call struct {
	*mock.Call
}

// RecordPanic is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricService_Expecter) RecordPanic(ctx interface{}) *MockMetricService_RecordPanic_Call {
	return &MockMetricService_RecordPanic_Call{Call: _e.mock.On("RecordPanic", ctx)}
}

func (_c *MockMetricService_RecordPanic_Call) Run(run func(ctx context.Context)) *MockMetricService_RecordPanic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMetricService_RecordPanic_Call) Return() *MockMetricService_RecordPanic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricService_RecordPanic_Call) RunAndReturn(run func(context.Context)) *MockMetricService_RecordPanic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricService creates a new instance of MockMetricService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricService {
	mock := &MockMetricService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
