// Code generated by mockery v2.39.1. DO NOT EDIT.

package sophrosyne

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ProfileService is an autogenerated mock type for the ProfileService type
type ProfileService struct {
	mock.Mock
}

type ProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileService) EXPECT() *ProfileService_Expecter {
	return &ProfileService_Expecter{mock: &_m.Mock}
}

// CreateProfile provides a mock function with given fields: ctx, profile
func (_m *ProfileService) CreateProfile(ctx context.Context, profile CreateProfileRequest) (Profile, error) {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateProfileRequest) (Profile, error)); ok {
		return rf(ctx, profile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateProfileRequest) Profile); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Get(0).(Profile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateProfileRequest) error); ok {
		r1 = rf(ctx, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileService_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type ProfileService_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile CreateProfileRequest
func (_e *ProfileService_Expecter) CreateProfile(ctx interface{}, profile interface{}) *ProfileService_CreateProfile_Call {
	return &ProfileService_CreateProfile_Call{Call: _e.mock.On("CreateProfile", ctx, profile)}
}

func (_c *ProfileService_CreateProfile_Call) Run(run func(ctx context.Context, profile CreateProfileRequest)) *ProfileService_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CreateProfileRequest))
	})
	return _c
}

func (_c *ProfileService_CreateProfile_Call) Return(_a0 Profile, _a1 error) *ProfileService_CreateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileService_CreateProfile_Call) RunAndReturn(run func(context.Context, CreateProfileRequest) (Profile, error)) *ProfileService_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfile provides a mock function with given fields: ctx, name
func (_m *ProfileService) DeleteProfile(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfileService_DeleteProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfile'
type ProfileService_DeleteProfile_Call struct {
	*mock.Call
}

// DeleteProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ProfileService_Expecter) DeleteProfile(ctx interface{}, name interface{}) *ProfileService_DeleteProfile_Call {
	return &ProfileService_DeleteProfile_Call{Call: _e.mock.On("DeleteProfile", ctx, name)}
}

func (_c *ProfileService_DeleteProfile_Call) Run(run func(ctx context.Context, name string)) *ProfileService_DeleteProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProfileService_DeleteProfile_Call) Return(_a0 error) *ProfileService_DeleteProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileService_DeleteProfile_Call) RunAndReturn(run func(context.Context, string) error) *ProfileService_DeleteProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, id
func (_m *ProfileService) GetProfile(ctx context.Context, id string) (Profile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Profile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Profile); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(Profile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type ProfileService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProfileService_Expecter) GetProfile(ctx interface{}, id interface{}) *ProfileService_GetProfile_Call {
	return &ProfileService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, id)}
}

func (_c *ProfileService_GetProfile_Call) Run(run func(ctx context.Context, id string)) *ProfileService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProfileService_GetProfile_Call) Return(_a0 Profile, _a1 error) *ProfileService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileService_GetProfile_Call) RunAndReturn(run func(context.Context, string) (Profile, error)) *ProfileService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileByName provides a mock function with given fields: ctx, name
func (_m *ProfileService) GetProfileByName(ctx context.Context, name string) (Profile, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByName")
	}

	var r0 Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Profile, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Profile); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(Profile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileService_GetProfileByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileByName'
type ProfileService_GetProfileByName_Call struct {
	*mock.Call
}

// GetProfileByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ProfileService_Expecter) GetProfileByName(ctx interface{}, name interface{}) *ProfileService_GetProfileByName_Call {
	return &ProfileService_GetProfileByName_Call{Call: _e.mock.On("GetProfileByName", ctx, name)}
}

func (_c *ProfileService_GetProfileByName_Call) Run(run func(ctx context.Context, name string)) *ProfileService_GetProfileByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProfileService_GetProfileByName_Call) Return(_a0 Profile, _a1 error) *ProfileService_GetProfileByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileService_GetProfileByName_Call) RunAndReturn(run func(context.Context, string) (Profile, error)) *ProfileService_GetProfileByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function with given fields: ctx, cursor
func (_m *ProfileService) GetProfiles(ctx context.Context, cursor *DatabaseCursor) ([]Profile, error) {
	ret := _m.Called(ctx, cursor)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DatabaseCursor) ([]Profile, error)); ok {
		return rf(ctx, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DatabaseCursor) []Profile); ok {
		r0 = rf(ctx, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DatabaseCursor) error); ok {
		r1 = rf(ctx, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileService_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type ProfileService_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor *DatabaseCursor
func (_e *ProfileService_Expecter) GetProfiles(ctx interface{}, cursor interface{}) *ProfileService_GetProfiles_Call {
	return &ProfileService_GetProfiles_Call{Call: _e.mock.On("GetProfiles", ctx, cursor)}
}

func (_c *ProfileService_GetProfiles_Call) Run(run func(ctx context.Context, cursor *DatabaseCursor)) *ProfileService_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*DatabaseCursor))
	})
	return _c
}

func (_c *ProfileService_GetProfiles_Call) Return(_a0 []Profile, _a1 error) *ProfileService_GetProfiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileService_GetProfiles_Call) RunAndReturn(run func(context.Context, *DatabaseCursor) ([]Profile, error)) *ProfileService_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, profile
func (_m *ProfileService) UpdateProfile(ctx context.Context, profile UpdateProfileRequest) (Profile, error) {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, UpdateProfileRequest) (Profile, error)); ok {
		return rf(ctx, profile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, UpdateProfileRequest) Profile); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Get(0).(Profile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, UpdateProfileRequest) error); ok {
		r1 = rf(ctx, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type ProfileService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile UpdateProfileRequest
func (_e *ProfileService_Expecter) UpdateProfile(ctx interface{}, profile interface{}) *ProfileService_UpdateProfile_Call {
	return &ProfileService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profile)}
}

func (_c *ProfileService_UpdateProfile_Call) Run(run func(ctx context.Context, profile UpdateProfileRequest)) *ProfileService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(UpdateProfileRequest))
	})
	return _c
}

func (_c *ProfileService_UpdateProfile_Call) Return(_a0 Profile, _a1 error) *ProfileService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileService_UpdateProfile_Call) RunAndReturn(run func(context.Context, UpdateProfileRequest) (Profile, error)) *ProfileService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewProfileService creates a new instance of ProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileService {
	mock := &ProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
