// Code generated by mockery v2.39.1. DO NOT EDIT.

package checks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CheckServiceClient is an autogenerated mock type for the CheckServiceClient type
type CheckServiceClient struct {
	mock.Mock
}

type CheckServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CheckServiceClient) EXPECT() *CheckServiceClient_Expecter {
	return &CheckServiceClient_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, in, opts
func (_m *CheckServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *CheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CheckRequest, ...grpc.CallOption) (*CheckResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CheckRequest, ...grpc.CallOption) *CheckResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CheckResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CheckRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckServiceClient_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type CheckServiceClient_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - in *CheckRequest
//   - opts ...grpc.CallOption
func (_e *CheckServiceClient_Expecter) Check(ctx interface{}, in interface{}, opts ...interface{}) *CheckServiceClient_Check_Call {
	return &CheckServiceClient_Check_Call{Call: _e.mock.On("Check",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CheckServiceClient_Check_Call) Run(run func(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption)) *CheckServiceClient_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*CheckRequest), variadicArgs...)
	})
	return _c
}

func (_c *CheckServiceClient_Check_Call) Return(_a0 *CheckResponse, _a1 error) *CheckServiceClient_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CheckServiceClient_Check_Call) RunAndReturn(run func(context.Context, *CheckRequest, ...grpc.CallOption) (*CheckResponse, error)) *CheckServiceClient_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewCheckServiceClient creates a new instance of CheckServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckServiceClient {
	mock := &CheckServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
