// Code generated by mockery v2.43.0. DO NOT EDIT.

package checks

import mock "github.com/stretchr/testify/mock"

// MockUnsafeCheckServiceServer is an autogenerated mock type for the UnsafeCheckServiceServer type
type MockUnsafeCheckServiceServer struct {
	mock.Mock
}

type MockUnsafeCheckServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeCheckServiceServer) EXPECT() *MockUnsafeCheckServiceServer_Expecter {
	return &MockUnsafeCheckServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedCheckServiceServer provides a mock function with given fields:
func (_m *MockUnsafeCheckServiceServer) mustEmbedUnimplementedCheckServiceServer() {
	_m.Called()
}

// MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCheckServiceServer'
type MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCheckServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeCheckServiceServer_Expecter) mustEmbedUnimplementedCheckServiceServer() *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	return &MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCheckServiceServer")}
}

func (_c *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) Run(run func()) *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) Return() *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) RunAndReturn(run func()) *MockUnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeCheckServiceServer creates a new instance of MockUnsafeCheckServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeCheckServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeCheckServiceServer {
	mock := &MockUnsafeCheckServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
