// Code generated by mockery v2.39.1. DO NOT EDIT.

package checks

import mock "github.com/stretchr/testify/mock"

// UnsafeCheckServiceServer is an autogenerated mock type for the UnsafeCheckServiceServer type
type UnsafeCheckServiceServer struct {
	mock.Mock
}

type UnsafeCheckServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeCheckServiceServer) EXPECT() *UnsafeCheckServiceServer_Expecter {
	return &UnsafeCheckServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedCheckServiceServer provides a mock function with given fields:
func (_m *UnsafeCheckServiceServer) mustEmbedUnimplementedCheckServiceServer() {
	_m.Called()
}

// UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCheckServiceServer'
type UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCheckServiceServer is a helper method to define mock.On call
func (_e *UnsafeCheckServiceServer_Expecter) mustEmbedUnimplementedCheckServiceServer() *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	return &UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCheckServiceServer")}
}

func (_c *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) Run(run func()) *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) Return() *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call) RunAndReturn(run func()) *UnsafeCheckServiceServer_mustEmbedUnimplementedCheckServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeCheckServiceServer creates a new instance of UnsafeCheckServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCheckServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCheckServiceServer {
	mock := &UnsafeCheckServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
