version = 1

test_patterns = [
  "tests/**/*",
  "**/*_test.go"
]

exclude_patterns = ["**/*.pb.go"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/MadsRC/sophrosyne"

[[transformers]]
name = "gofmt"