run:
  tests: true
  build-tags:
    - integration
output:
  formats:
    - format: checkstyle
      path: build/report.xml
    - format: colored-line-number
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - gosec
    - forbidigo
    - godot
    - errname
    - errorlint
    - asasalint
    - asciicheck
    - bidichk
    - errchkjson
    - gochecknoinits
#    - wrapcheck
    - sloglint
    - tenv
linters-settings:
  goimports:
    local-prefixes: github.com/madsrc/sophrosyne
  errorlint:
    errorf: false
