[tools]
go = "1.22.6"
watchexec = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.58.1"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/google/osv-scanner/cmd/osv-scanner" = "v1"
"pipx:pre-commit" = "3.7.1"
protoc = "26.1"
mockery = "2.43.1"
protoc-gen-go = "1.34.1"
protoc-gen-go-grpc = "1.3.0"
node = "22.6.0"
"go:github.com/goreleaser/goreleaser" = "1.26.1"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "latest"

[settings]
experimental = true
go_set_gobin = true
