[tools]
go = "1.22.3"
watchexec = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.58.1"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/google/osv-scanner/cmd/osv-scanner" = "v1"
"pipx:pre-commit" = "latest"
protoc = "latest"
mockery = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
node = "latest"

[settings]
experimental = true
go_set_gobin = true
