repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: end-of-file-fixer
        exclude: "snapshots|docs/api.md"
      - id: trailing-whitespace
        exclude: "snapshots|docs/api.md"
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-executables-have-shebangs
