repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/osv-scanner/
    rev: v1.8.4 # v1.7.3
    hooks:
      - id: osv-scanner
        args: ["-r", "."]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix']
ci:
  skip:
    - osv-scanner # Handled by a dedicated GitHub Action
