services:

  db:
    image: postgres@sha256:e891dea3db3b3472b8cabe37af00563c9e05b0d7726be5ef7ff0e39be8db61a9
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  otelcollector:
    image: otel/opentelemetry-collector@sha256:24772c8b8e4acc4e2e4b22332c0bced1aaa83586b9fc0a67a047b1cffb7f5c72
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configurations/dev-otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "55679:55679" # otel interface
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:075b1ba2c4ebb04bc3a6ab86c06ec8d8099f8fda1c96ef6d104d9bb1def1d8bc
    ports:
      - 9090:9090
    volumes:
      - ./configurations/dev-prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: --web.enable-remote-write-receiver --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss@sha256:0df353752836543516fbd45184496d725a103b0b42d6037dfb78eb741a7a7860
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.58@sha256:f015fb34e6742bb46b87c42cf83abfacfdd5dc39864a859a4ba942eb21c4b29c
    ports:
      - 5778:5778
      - 16686:16686
