services:

  db:
    image: postgres@sha256:59c554e6f26822fd489ebbdef431457db2debd0c5762b24f11f603db5b91dfcc
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  otelcollector:
    image: otel/opentelemetry-collector@sha256:aef3e6d742fb69b94e9c0813a028449d28438bb6f9c93cb5d0b8d0704b78ae65
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configurations/dev-otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "55679:55679" # otel interface
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:cafe963e591c872d38f3ea41ff8eb22cee97917b7c97b5c0ccd43a419f11f613
    ports:
      - 9090:9090
    volumes:
      - ./configurations/dev-prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: --web.enable-remote-write-receiver --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss@sha256:420dfcbe22c71da8774b82b2e9ece02382fa210174bb8f342c922d04afdc0f0f
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e
    ports:
      - 5778:5778
      - 16686:16686
