services:

  db:
    image: postgres@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  otelcollector:
    image: otel/opentelemetry-collector@sha256:1cffbc33556826c5185cebc1b1dbe1e056b3417bd422cdd4a03747dc6d19388f
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configurations/dev-otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "55679:55679" # otel interface
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:5c435642ca4d8427ca26f4901c11114023004709037880cd7860d5b7176aa731
    ports:
      - 9090:9090
    volumes:
      - ./configurations/dev-prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: --web.enable-remote-write-receiver --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.57@sha256:8f165334f418ca53691ce358c19b4244226ed35c5d18408c5acf305af2065fb9
    ports:
      - 5778:5778
      - 16686:16686
