services:

  db:
    image: postgres@sha256:8d3be35b184e70d81e54cbcbd3df3c0b47f37d06482c0dd1c140db5dbcc6a808
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  otelcollector:
    image: otel/opentelemetry-collector@sha256:7020db3692a3d722fec002f39608ffe3a5d2fa4d09e14607cf33b9416f2c1df8
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configurations/dev-otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "55679:55679" # otel interface
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:378f4e03703557d1c6419e6caccf922f96e6d88a530f7431d66a4c4f4b1000fe
    ports:
      - 9090:9090
    volumes:
      - ./configurations/dev-prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: --web.enable-remote-write-receiver --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss@sha256:d5133220d770aba5cb655147b619fa8770b90f41d8489a821d33b1cd34d16f89
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e
    ports:
      - 5778:5778
      - 16686:16686
