services:

  db:
    image: postgres@sha256:f176fef320ed02c347e9f85352620945547a9a23038f02b57cf7939a198182ae
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  otelcollector:
    image: otel/opentelemetry-collector@sha256:756725f13cfbd34be6d7210419e06243f078090f6190a637b766beb4293417cf
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configurations/dev-otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "55679:55679" # otel interface
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:3b9b2a15d376334da8c286d995777d3b9315aa666d2311170ada6059a517b74f
    ports:
      - 9090:9090
    volumes:
      - ./configurations/dev-prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: --web.enable-remote-write-receiver --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e
    ports:
      - 5778:5778
      - 16686:16686
