#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="Generate mocks for interfaces"
# mise sources=[".mockery.yaml", "go.mod", "go.sum", "internal/**/*", "cmd/**/*", "*.go"]
# mise outputs=["build/.mocksentinel"]

mkdir -p build

check=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --check) check=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

mkdir -p build/backups
echo "Backing up mocks to build/backups/mocks..."
rm -rf build/backups/mocks
mv internal/mocks build/backups/mocks

mockery
touch build/.mocksentinel

if test "$check" = 0; then
  echo "\nChecking mocks..."
  changes=$(git status --porcelain internal/mocks)
  if test -n "$changes"; then
    echo "Mocks changed:"
    git --no-pager diff internal/mocks
    exit 1
  fi
  echo "Mocks have no changes according to git!"
fi
