#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="generate GRPC code"
# mise sources=["proto/**/*.proto"]
# mise outputs=["build/.protobufsentinel"]

mkdir -p build

check=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --check) check=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

anyProtoChecksum="bcf5de6ce463b1a38ff76b77955aa7e580b4ec12af34a927b1d45c9efb0faf66"
emptyProtoChecksum="ecef3d54cc9e079673b9816c67bac770f7f3bf6dada2d4596ba69d71daa971e6"

mkdir -p proto/google/protobuf

curl -s -o proto/google/protobuf/any.proto https://raw.githubusercontent.com/protocolbuffers/protobuf/a978b75794a6ce4547c9db08a115c458d9190934/src/google/protobuf/any.proto

if test "$(sha256sum proto/google/protobuf/any.proto | cut -d' ' -f1)" != "$anyProtoChecksum"; then
  echo "Checksum mismatch for proto/google/protobuf/any.proto" >&2
  exit 1
fi

curl -s -o proto/google/protobuf/empty.proto https://raw.githubusercontent.com/protocolbuffers/protobuf/a978b75794a6ce4547c9db08a115c458d9190934/src/google/protobuf/empty.proto

if test "$(sha256sum proto/google/protobuf/empty.proto | cut -d' ' -f1)" != "$emptyProtoChecksum"; then
  echo "Checksum mismatch for proto/google/protobuf/empty.proto" >&2
  exit 1
fi

protoc \
--proto_path=proto \
--go_out=internal/grpc \
--go_opt=paths=source_relative \
--go-grpc_out=internal/grpc \
--go-grpc_opt=paths=source_relative \
proto/sophrosyne/v0/*

touch build/.protobufsentinel

if test "$check" = 0; then
  echo "\nChecking GRPC files..."
  changes=$(git status --porcelain internal/grpc)
  if test -n "$changes"; then
    echo "GRPC files changed:"
    git --no-pager diff internal/grpc
    exit 1
  fi
  echo "GRPC files have no changes according to git!"
fi
