#!/bin/sh
# mise sources=["proto/**/*.proto"]
# mise outputs=["build/.protobufsentinel"]

set -e

mkdir -p build

check=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --check) check=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

mkdir -p internal/grpc/checks
mkdir -p build/backups/grpc
echo "Backing up GRPC files to build/backups/grpc/checks"
mv -f internal/grpc/checks build/backups/grpc/checks
rm -rf internal/grpc/checks

protoc \
--proto_path=proto \
--go_out=internal/grpc \
--go_opt=paths=source_relative \
--go-grpc_out=internal/grpc \
--go-grpc_opt=paths=source_relative \
proto/checks/checks.proto

touch build/.protobufsentinel

if test "$check" = 0; then
  echo "\nChecking GRPC files..."
  changes=$(git status --porcelain internal/grpc)
  if test -n "$changes"; then
    echo "GRPC files changed:"
    git --no-pager diff internal/grpc
    exit 1
  fi
  echo "GRPC files have no changes according to git!"
fi
