#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="Sync the go version defined in go.mod to relevant files"

version=$(grep -E "^go .*$" go.mod | awk '{print $2}')

echo "Version extracted from go.mod: $version"

echo "Setting go version in .mise.toml"
mise use "go@$version"

echo "Setting go version in .idea/workspace.xml"
sed -i "s/.local\/share\/mise\/installs\/go\/.*\"/.local\/share\/mise\/installs\/go\/$version\"/g" .idea/workspace.xml
