// Sophrosyne
//   Copyright (C) 2024  Mads R. Havmand
//
// This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: sophrosyne/v0/checkProvider.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request message for Scan.
// text is the text to scan.
// image is the image to scan.
type CheckProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Check:
	//
	//	*CheckProviderRequest_Text
	//	*CheckProviderRequest_Image
	Check isCheckProviderRequest_Check `protobuf_oneof:"check"`
}

func (x *CheckProviderRequest) Reset() {
	*x = CheckProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophrosyne_v0_checkProvider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProviderRequest) ProtoMessage() {}

func (x *CheckProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophrosyne_v0_checkProvider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProviderRequest.ProtoReflect.Descriptor instead.
func (*CheckProviderRequest) Descriptor() ([]byte, []int) {
	return file_sophrosyne_v0_checkProvider_proto_rawDescGZIP(), []int{0}
}

func (m *CheckProviderRequest) GetCheck() isCheckProviderRequest_Check {
	if m != nil {
		return m.Check
	}
	return nil
}

func (x *CheckProviderRequest) GetText() string {
	if x, ok := x.GetCheck().(*CheckProviderRequest_Text); ok {
		return x.Text
	}
	return ""
}

func (x *CheckProviderRequest) GetImage() []byte {
	if x, ok := x.GetCheck().(*CheckProviderRequest_Image); ok {
		return x.Image
	}
	return nil
}

type isCheckProviderRequest_Check interface {
	isCheckProviderRequest_Check()
}

type CheckProviderRequest_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type CheckProviderRequest_Image struct {
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*CheckProviderRequest_Text) isCheckProviderRequest_Check() {}

func (*CheckProviderRequest_Image) isCheckProviderRequest_Check() {}

// *
// Response message for Scan.
// result indicates that whether or not the scan found what it was looking for. For a scan that looks for toxicity, a true value indicates that the scan found toxic text.
// Checks is a list of the checks that were run, their individual results and any potential details.
type CheckProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  bool       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Details *anypb.Any `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CheckProviderResponse) Reset() {
	*x = CheckProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophrosyne_v0_checkProvider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProviderResponse) ProtoMessage() {}

func (x *CheckProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophrosyne_v0_checkProvider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProviderResponse.ProtoReflect.Descriptor instead.
func (*CheckProviderResponse) Descriptor() ([]byte, []int) {
	return file_sophrosyne_v0_checkProvider_proto_rawDescGZIP(), []int{1}
}

func (x *CheckProviderResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CheckProviderResponse) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_sophrosyne_v0_checkProvider_proto protoreflect.FileDescriptor

var file_sophrosyne_v0_checkProvider_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2f, 0x76, 0x30, 0x2f,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e,
	0x76, 0x30, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x5f, 0x0a, 0x15,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x6c, 0x0a,
	0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x23,
	0x2e, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x64, 0x73, 0x72, 0x63,
	0x2f, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f,
	0x73, 0x79, 0x6e, 0x65, 0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sophrosyne_v0_checkProvider_proto_rawDescOnce sync.Once
	file_sophrosyne_v0_checkProvider_proto_rawDescData = file_sophrosyne_v0_checkProvider_proto_rawDesc
)

func file_sophrosyne_v0_checkProvider_proto_rawDescGZIP() []byte {
	file_sophrosyne_v0_checkProvider_proto_rawDescOnce.Do(func() {
		file_sophrosyne_v0_checkProvider_proto_rawDescData = protoimpl.X.CompressGZIP(file_sophrosyne_v0_checkProvider_proto_rawDescData)
	})
	return file_sophrosyne_v0_checkProvider_proto_rawDescData
}

var file_sophrosyne_v0_checkProvider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sophrosyne_v0_checkProvider_proto_goTypes = []interface{}{
	(*CheckProviderRequest)(nil),  // 0: sophrosyne.v0.CheckProviderRequest
	(*CheckProviderResponse)(nil), // 1: sophrosyne.v0.CheckProviderResponse
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
}
var file_sophrosyne_v0_checkProvider_proto_depIdxs = []int32{
	2, // 0: sophrosyne.v0.CheckProviderResponse.details:type_name -> google.protobuf.Any
	0, // 1: sophrosyne.v0.CheckProviderService.Check:input_type -> sophrosyne.v0.CheckProviderRequest
	1, // 2: sophrosyne.v0.CheckProviderService.Check:output_type -> sophrosyne.v0.CheckProviderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sophrosyne_v0_checkProvider_proto_init() }
func file_sophrosyne_v0_checkProvider_proto_init() {
	if File_sophrosyne_v0_checkProvider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sophrosyne_v0_checkProvider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophrosyne_v0_checkProvider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sophrosyne_v0_checkProvider_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CheckProviderRequest_Text)(nil),
		(*CheckProviderRequest_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sophrosyne_v0_checkProvider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sophrosyne_v0_checkProvider_proto_goTypes,
		DependencyIndexes: file_sophrosyne_v0_checkProvider_proto_depIdxs,
		MessageInfos:      file_sophrosyne_v0_checkProvider_proto_msgTypes,
	}.Build()
	File_sophrosyne_v0_checkProvider_proto = out.File
	file_sophrosyne_v0_checkProvider_proto_rawDesc = nil
	file_sophrosyne_v0_checkProvider_proto_goTypes = nil
	file_sophrosyne_v0_checkProvider_proto_depIdxs = nil
}
