// Sophrosyne
//   Copyright (C) 2024  Mads R. Havmand
//
// This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: sophrosyne/v0/scans.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request message for Scan.
// profile is the name of the profile to use. If no profile is provided, the default profile will be used.
// text is the raw text to scan in UTF-8.
// image is the image to scan.
type ScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// Types that are assignable to Kind:
	//
	//	*ScanRequest_Text
	//	*ScanRequest_Image
	Kind isScanRequest_Kind `protobuf_oneof:"kind"`
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophrosyne_v0_scans_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophrosyne_v0_scans_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_sophrosyne_v0_scans_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (m *ScanRequest) GetKind() isScanRequest_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *ScanRequest) GetText() string {
	if x, ok := x.GetKind().(*ScanRequest_Text); ok {
		return x.Text
	}
	return ""
}

func (x *ScanRequest) GetImage() []byte {
	if x, ok := x.GetKind().(*ScanRequest_Image); ok {
		return x.Image
	}
	return nil
}

type isScanRequest_Kind interface {
	isScanRequest_Kind()
}

type ScanRequest_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type ScanRequest_Image struct {
	Image []byte `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

func (*ScanRequest_Text) isScanRequest_Kind() {}

func (*ScanRequest_Image) isScanRequest_Kind() {}

// *
// Response message for Scan.
// result indicates that whether or not the scan found what it was looking for. For a scan that looks for toxicity, a true value indicates that the scan found toxic text.
// Checks is a list of the checks that were run, their individual results and any potential details.
type ScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Checks []*CheckResult `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophrosyne_v0_scans_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophrosyne_v0_scans_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_sophrosyne_v0_scans_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ScanResponse) GetChecks() []*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

// *
// Result from an individual check.
// name is the name of the check.
// result indicates whether the check found what it was looking for.
// details indicates any potential details.
type CheckResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Result  bool       `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Details *anypb.Any `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophrosyne_v0_scans_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_sophrosyne_v0_scans_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_sophrosyne_v0_scans_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CheckResult) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_sophrosyne_v0_scans_proto protoreflect.FileDescriptor

var file_sophrosyne_v0_scans_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2f, 0x76, 0x30, 0x2f,
	0x73, 0x63, 0x61, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x6f, 0x70,
	0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e, 0x76, 0x30, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x22, 0x5a, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x32, 0x0a, 0x06,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73,
	0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73,
	0x22, 0x69, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x4e, 0x0a, 0x0b, 0x53,
	0x63, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x53, 0x63,
	0x61, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e,
	0x76, 0x30, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x64, 0x73, 0x72, 0x63,
	0x2f, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f, 0x73, 0x79, 0x6e, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6f, 0x70, 0x68, 0x72, 0x6f,
	0x73, 0x79, 0x6e, 0x65, 0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sophrosyne_v0_scans_proto_rawDescOnce sync.Once
	file_sophrosyne_v0_scans_proto_rawDescData = file_sophrosyne_v0_scans_proto_rawDesc
)

func file_sophrosyne_v0_scans_proto_rawDescGZIP() []byte {
	file_sophrosyne_v0_scans_proto_rawDescOnce.Do(func() {
		file_sophrosyne_v0_scans_proto_rawDescData = protoimpl.X.CompressGZIP(file_sophrosyne_v0_scans_proto_rawDescData)
	})
	return file_sophrosyne_v0_scans_proto_rawDescData
}

var file_sophrosyne_v0_scans_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sophrosyne_v0_scans_proto_goTypes = []interface{}{
	(*ScanRequest)(nil),  // 0: sophrosyne.v0.ScanRequest
	(*ScanResponse)(nil), // 1: sophrosyne.v0.ScanResponse
	(*CheckResult)(nil),  // 2: sophrosyne.v0.CheckResult
	(*anypb.Any)(nil),    // 3: google.protobuf.Any
}
var file_sophrosyne_v0_scans_proto_depIdxs = []int32{
	2, // 0: sophrosyne.v0.ScanResponse.checks:type_name -> sophrosyne.v0.CheckResult
	3, // 1: sophrosyne.v0.CheckResult.details:type_name -> google.protobuf.Any
	0, // 2: sophrosyne.v0.ScanService.Scan:input_type -> sophrosyne.v0.ScanRequest
	1, // 3: sophrosyne.v0.ScanService.Scan:output_type -> sophrosyne.v0.ScanResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sophrosyne_v0_scans_proto_init() }
func file_sophrosyne_v0_scans_proto_init() {
	if File_sophrosyne_v0_scans_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sophrosyne_v0_scans_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophrosyne_v0_scans_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophrosyne_v0_scans_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sophrosyne_v0_scans_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ScanRequest_Text)(nil),
		(*ScanRequest_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sophrosyne_v0_scans_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sophrosyne_v0_scans_proto_goTypes,
		DependencyIndexes: file_sophrosyne_v0_scans_proto_depIdxs,
		MessageInfos:      file_sophrosyne_v0_scans_proto_msgTypes,
	}.Build()
	File_sophrosyne_v0_scans_proto = out.File
	file_sophrosyne_v0_scans_proto_rawDesc = nil
	file_sophrosyne_v0_scans_proto_goTypes = nil
	file_sophrosyne_v0_scans_proto_depIdxs = nil
}
