#!/bin/sh
# mise sources=["go.mod", "go.sum", "internal/**/*", "cmd/**/*", "*.go"]
# mise outputs=["build/unit_coverage.out", "build/unit_test_report.json"]

ci=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --ci) ci=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

mkdir -p build

if test "$ci" = 0; then
  go test -coverprofile build/unit_coverage.out -json ./... > build/unit_test_report.json
else
  go test -coverprofile build/unit_coverage.out ./...
fi
