#!/bin/sh
# mise sources=["go.mod", "go.sum", "internal/**/*", "cmd/**/*", "*.go"]
# mise outputs=["build/unit_coverage.out", "build/unit_test_report.json"]

mkdir -p build

go test -json ./... > build/unit_test_report.json || true
go test -coverprofile build/unit_coverage.out ./...
