#!/bin/sh
# mise sources=["go.mod", "go.sum", "internal/**/*", "cmd/**/*", "*.go"]
# mise outputs=["build/report.xml"]

check=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --check) check=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

if test "$check" = 0; then
  changes=$(goimports -l -local github.com/madsrc/sophrosyne -e .)
  if test -n "$changes"; then
    echo "$changes"
    exit 1
  else
    exit 0
  fi
else
  goimports -w -local github.com/madsrc/sophrosyne -e .
fi
