#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="Run code formatting"

check=1

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --check) check=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

if test "$check" = 0; then
  changes=$(goimports -l -local github.com/madsrc/sophrosyne -e .)
  if test -n "$changes"; then
    echo "$changes"
    exit 1
  else
    exit 0
  fi
else
  goimports -w -local github.com/madsrc/sophrosyne -e $(find . -name "*.go" | grep -v "\./build\|\./internal/mocks\|.*\.pb\.go")
fi
