#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="Run code linting tools"
# mise sources=["go.mod", "go.sum", "internal/**/*", "cmd/**/*", "*.go", ".golangci.yaml]
# mise outputs=["build/report.xml"]

nofail=1
fix=1

fixflag=""

handle_argument() {
  echo "Argument '$1' not supported" >&2; exit 1
}

while test "$#" -gt 0; do
  case "$1" in
    --no-fail) nofail=0; shift 1;;
    --fix) fix=0; shift 1;;

    -*) echo "unknown option: $1" >&2; exit 1;;
    *) handle_argument "$1"; shift 1;;
  esac
done

if test "$fix" = 0; then
  fixflags="--fix"
fi

golangci-lint run \
--issues-exit-code="$nofail" \
--max-issues-per-linter 0 \
--max-same-issues 0 \
$fixflags
