#!/bin/sh
#
# Sophrosyne
#   Copyright (C) 2024  Mads R. Havmand
#
# This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
# mise description="Run development environment"

docker compose -f docker-compose.development.yml up -d
SOPH_LOGGING_LEVEL=debug \
  SOPH_TRACING_OUTPUT=http \
  SOPH_METRICS_OUTPUT=http \
  SOPH_METRICS_ENABLED=true \
  SOPH_TRACING_ENABLED=true \
  OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318" \
  OTEL_TRACES_EXPORTER="otlp" \
  OTEL_METRICS_EXPORTER="otlp" \
  OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf" \
go run cmd/sophrosyne/main.go --config configurations/dev.yaml run
