#!/bin/sh
# mise outputs=[]

docker compose -f docker-compose.development.yml up -d
SOPH_LOGGING_LEVEL=debug \
  SOPH_TRACING_OUTPUT=http \
  SOPH_METRICS_OUTPUT=http \
  SOPH_METRICS_ENABLED=true \
  SOPH_TRACING_ENABLED=true \
  OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318" \
  OTEL_TRACES_EXPORTER="otlp" \
  OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf" \
go run cmd/sophrosyne/main.go --config configurations/dev.yaml run
