security:
  site_key: '6fAkguc1RQkgdWwoLdslkQjA/N5ujPvGEmG2l97Gt+4='
  salt: 'KULByt65QDNWy4BhtkOagb3td08q992ZfPWLthFw00s='
development:
  static_root_token: "thisisastaticroottoken"
logging:
  format: development
