database:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  name: postgres
security:
  siteKey: !!binary ZD+b96+IBJranGUCEMZzi2yhrA7eRyrqwgCTYhEG7oIyNz3mcvEjGqC/RRF+rLtpfD+Jbb5DzVlmUM1TlL80BQ==
  salt: !!binary Ag4k628yFI2h+SWoypEO7OYzrFqBrEz8az9c6Du7ons=
development:
  staticRootToken: staticroottoken
