# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sophrosyne.grpc.checks import checks_pb2 as sophrosyne_dot_grpc_dot_checks_dot_checks__pb2


class CheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/checks.v1.CheckService/Check',
                request_serializer=sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckRequest.SerializeToString,
                response_deserializer=sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckResponse.FromString,
                )


class CheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckRequest.FromString,
                    response_serializer=sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checks.v1.CheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checks.v1.CheckService/Check',
            sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckRequest.SerializeToString,
            sophrosyne_dot_grpc_dot_checks_dot_checks__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
