# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sophrosyne/grpc/checks/checks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sophrosyne/grpc/checks/checks.proto\x12\tchecks.v1\"8\n\x0c\x43heckRequest\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x0f\n\x05image\x18\x02 \x01(\tH\x00\x42\x07\n\x05\x63heck\"0\n\rCheckResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2L\n\x0c\x43heckService\x12<\n\x05\x43heck\x12\x17.checks.v1.CheckRequest\x1a\x18.checks.v1.CheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sophrosyne.grpc.checks.checks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKREQUEST']._serialized_start=50
  _globals['_CHECKREQUEST']._serialized_end=106
  _globals['_CHECKRESPONSE']._serialized_start=108
  _globals['_CHECKRESPONSE']._serialized_end=156
  _globals['_CHECKSERVICE']._serialized_start=158
  _globals['_CHECKSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
