// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v0 "github.com/madsrc/sophrosyne/internal/grpc/sophrosyne/v0"
)

// MockCheckProviderServiceClient is an autogenerated mock type for the CheckProviderServiceClient type
type MockCheckProviderServiceClient struct {
	mock.Mock
}

type MockCheckProviderServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckProviderServiceClient) EXPECT() *MockCheckProviderServiceClient_Expecter {
	return &MockCheckProviderServiceClient_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, in, opts
func (_m *MockCheckProviderServiceClient) Check(ctx context.Context, in *v0.CheckProviderRequest, opts ...grpc.CallOption) (*v0.CheckProviderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *v0.CheckProviderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v0.CheckProviderRequest, ...grpc.CallOption) (*v0.CheckProviderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v0.CheckProviderRequest, ...grpc.CallOption) *v0.CheckProviderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v0.CheckProviderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v0.CheckProviderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCheckProviderServiceClient_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockCheckProviderServiceClient_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v0.CheckProviderRequest
//   - opts ...grpc.CallOption
func (_e *MockCheckProviderServiceClient_Expecter) Check(ctx interface{}, in interface{}, opts ...interface{}) *MockCheckProviderServiceClient_Check_Call {
	return &MockCheckProviderServiceClient_Check_Call{Call: _e.mock.On("Check",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCheckProviderServiceClient_Check_Call) Run(run func(ctx context.Context, in *v0.CheckProviderRequest, opts ...grpc.CallOption)) *MockCheckProviderServiceClient_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v0.CheckProviderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCheckProviderServiceClient_Check_Call) Return(_a0 *v0.CheckProviderResponse, _a1 error) *MockCheckProviderServiceClient_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCheckProviderServiceClient_Check_Call) RunAndReturn(run func(context.Context, *v0.CheckProviderRequest, ...grpc.CallOption) (*v0.CheckProviderResponse, error)) *MockCheckProviderServiceClient_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckProviderServiceClient creates a new instance of MockCheckProviderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckProviderServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckProviderServiceClient {
	mock := &MockCheckProviderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
