// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import (
	context "context"

	v0 "github.com/madsrc/sophrosyne/internal/grpc/sophrosyne/v0"
	mock "github.com/stretchr/testify/mock"
)

// MockCheckProviderServiceServer is an autogenerated mock type for the CheckProviderServiceServer type
type MockCheckProviderServiceServer struct {
	mock.Mock
}

type MockCheckProviderServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckProviderServiceServer) EXPECT() *MockCheckProviderServiceServer_Expecter {
	return &MockCheckProviderServiceServer_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: _a0, _a1
func (_m *MockCheckProviderServiceServer) Check(_a0 context.Context, _a1 *v0.CheckProviderRequest) (*v0.CheckProviderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *v0.CheckProviderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v0.CheckProviderRequest) (*v0.CheckProviderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v0.CheckProviderRequest) *v0.CheckProviderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v0.CheckProviderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v0.CheckProviderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCheckProviderServiceServer_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockCheckProviderServiceServer_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *v0.CheckProviderRequest
func (_e *MockCheckProviderServiceServer_Expecter) Check(_a0 interface{}, _a1 interface{}) *MockCheckProviderServiceServer_Check_Call {
	return &MockCheckProviderServiceServer_Check_Call{Call: _e.mock.On("Check", _a0, _a1)}
}

func (_c *MockCheckProviderServiceServer_Check_Call) Run(run func(_a0 context.Context, _a1 *v0.CheckProviderRequest)) *MockCheckProviderServiceServer_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v0.CheckProviderRequest))
	})
	return _c
}

func (_c *MockCheckProviderServiceServer_Check_Call) Return(_a0 *v0.CheckProviderResponse, _a1 error) *MockCheckProviderServiceServer_Check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCheckProviderServiceServer_Check_Call) RunAndReturn(run func(context.Context, *v0.CheckProviderRequest) (*v0.CheckProviderResponse, error)) *MockCheckProviderServiceServer_Check_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedCheckProviderServiceServer provides a mock function with given fields:
func (_m *MockCheckProviderServiceServer) mustEmbedUnimplementedCheckProviderServiceServer() {
	_m.Called()
}

// MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedCheckProviderServiceServer'
type MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedCheckProviderServiceServer is a helper method to define mock.On call
func (_e *MockCheckProviderServiceServer_Expecter) mustEmbedUnimplementedCheckProviderServiceServer() *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call {
	return &MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedCheckProviderServiceServer")}
}

func (_c *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call) Run(run func()) *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call) Return() *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call) RunAndReturn(run func()) *MockCheckProviderServiceServer_mustEmbedUnimplementedCheckProviderServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckProviderServiceServer creates a new instance of MockCheckProviderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckProviderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckProviderServiceServer {
	mock := &MockCheckProviderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
