// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import mock "github.com/stretchr/testify/mock"

// MockisGetUserRequest_User is an autogenerated mock type for the isGetUserRequest_User type
type MockisGetUserRequest_User struct {
	mock.Mock
}

type MockisGetUserRequest_User_Expecter struct {
	mock *mock.Mock
}

func (_m *MockisGetUserRequest_User) EXPECT() *MockisGetUserRequest_User_Expecter {
	return &MockisGetUserRequest_User_Expecter{mock: &_m.Mock}
}

// isGetUserRequest_User provides a mock function with given fields:
func (_m *MockisGetUserRequest_User) isGetUserRequest_User() {
	_m.Called()
}

// MockisGetUserRequest_User_isGetUserRequest_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isGetUserRequest_User'
type MockisGetUserRequest_User_isGetUserRequest_User_Call struct {
	*mock.Call
}

// isGetUserRequest_User is a helper method to define mock.On call
func (_e *MockisGetUserRequest_User_Expecter) isGetUserRequest_User() *MockisGetUserRequest_User_isGetUserRequest_User_Call {
	return &MockisGetUserRequest_User_isGetUserRequest_User_Call{Call: _e.mock.On("isGetUserRequest_User")}
}

func (_c *MockisGetUserRequest_User_isGetUserRequest_User_Call) Run(run func()) *MockisGetUserRequest_User_isGetUserRequest_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockisGetUserRequest_User_isGetUserRequest_User_Call) Return() *MockisGetUserRequest_User_isGetUserRequest_User_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockisGetUserRequest_User_isGetUserRequest_User_Call) RunAndReturn(run func()) *MockisGetUserRequest_User_isGetUserRequest_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockisGetUserRequest_User creates a new instance of MockisGetUserRequest_User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockisGetUserRequest_User(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockisGetUserRequest_User {
	mock := &MockisGetUserRequest_User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
