// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import mock "github.com/stretchr/testify/mock"

// MockisGetProfileRequest_Profile is an autogenerated mock type for the isGetProfileRequest_Profile type
type MockisGetProfileRequest_Profile struct {
	mock.Mock
}

type MockisGetProfileRequest_Profile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockisGetProfileRequest_Profile) EXPECT() *MockisGetProfileRequest_Profile_Expecter {
	return &MockisGetProfileRequest_Profile_Expecter{mock: &_m.Mock}
}

// isGetProfileRequest_Profile provides a mock function with given fields:
func (_m *MockisGetProfileRequest_Profile) isGetProfileRequest_Profile() {
	_m.Called()
}

// MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isGetProfileRequest_Profile'
type MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call struct {
	*mock.Call
}

// isGetProfileRequest_Profile is a helper method to define mock.On call
func (_e *MockisGetProfileRequest_Profile_Expecter) isGetProfileRequest_Profile() *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call {
	return &MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call{Call: _e.mock.On("isGetProfileRequest_Profile")}
}

func (_c *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call) Run(run func()) *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call) Return() *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call) RunAndReturn(run func()) *MockisGetProfileRequest_Profile_isGetProfileRequest_Profile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockisGetProfileRequest_Profile creates a new instance of MockisGetProfileRequest_Profile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockisGetProfileRequest_Profile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockisGetProfileRequest_Profile {
	mock := &MockisGetProfileRequest_Profile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
