// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import mock "github.com/stretchr/testify/mock"

// MockUnsafeUserServiceServer is an autogenerated mock type for the UnsafeUserServiceServer type
type MockUnsafeUserServiceServer struct {
	mock.Mock
}

type MockUnsafeUserServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeUserServiceServer) EXPECT() *MockUnsafeUserServiceServer_Expecter {
	return &MockUnsafeUserServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedUserServiceServer provides a mock function with given fields:
func (_m *MockUnsafeUserServiceServer) mustEmbedUnimplementedUserServiceServer() {
	_m.Called()
}

// MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedUserServiceServer'
type MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedUserServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeUserServiceServer_Expecter) mustEmbedUnimplementedUserServiceServer() *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call {
	return &MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedUserServiceServer")}
}

func (_c *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call) Run(run func()) *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call) Return() *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call) RunAndReturn(run func()) *MockUnsafeUserServiceServer_mustEmbedUnimplementedUserServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeUserServiceServer creates a new instance of MockUnsafeUserServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeUserServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeUserServiceServer {
	mock := &MockUnsafeUserServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
