// Code generated by mockery v2.43.2. DO NOT EDIT.

package v0

import mock "github.com/stretchr/testify/mock"

// MockUnsafeProfileServiceServer is an autogenerated mock type for the UnsafeProfileServiceServer type
type MockUnsafeProfileServiceServer struct {
	mock.Mock
}

type MockUnsafeProfileServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeProfileServiceServer) EXPECT() *MockUnsafeProfileServiceServer_Expecter {
	return &MockUnsafeProfileServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProfileServiceServer provides a mock function with given fields:
func (_m *MockUnsafeProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {
	_m.Called()
}

// MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProfileServiceServer'
type MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProfileServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeProfileServiceServer_Expecter) mustEmbedUnimplementedProfileServiceServer() *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call {
	return &MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProfileServiceServer")}
}

func (_c *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call) Run(run func()) *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call) Return() *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call) RunAndReturn(run func()) *MockUnsafeProfileServiceServer_mustEmbedUnimplementedProfileServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeProfileServiceServer creates a new instance of MockUnsafeProfileServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeProfileServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeProfileServiceServer {
	mock := &MockUnsafeProfileServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
