concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  pull_request:
      types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions: read-all

name: Code Generation Check
jobs:
  check-codegen:
    permissions:
      pull-requests: write
    strategy:
      matrix:
        target: [ mocks, protobuf ]
      fail-fast: false # Don't cancel running checks because one fails
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2.1.0
      with:
        experimental: true
    - id: generate
      run: mise run generate:${{ matrix.target }} --check
      continue-on-error: true
    - name: Comment PR - Failure
      if: steps.generate.outcome == 'failure'
      uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
      with:
        comment_tag: 'code_gen_${{ matrix.target }}'
        mode: upsert
        message: |
          Generating the ${{ matrix.target }} code failed. This could be an indicator that the code generation is not up to date.
          Please review the failed action before deciding to merge the PR.
    - name: Comment PR - Success
      if: steps.generate.outcome != 'failure'
      uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
      with:
        comment_tag: 'code_gen_${{ matrix.target }}'
        mode: delete
        message: "The content of this message means nothing as the action will delete a message, not post it - I don't know why a message is needed here."
