concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions: read-all

name: SonarCloud analysis
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2.1.1
      with:
        experimental: true
    - run: mise run dev:lint --no-fail
    - run: mise run test:unit
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@9f9bba2c7aaf7a55eac26abbac906c3021d211b2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
