# Prime cache, as per https://medium.com/@everton.spader/how-to-cache-package-dependencies-between-branches-with-github-actions-e6a19f33783a
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

# Declare default permissions as read only.
permissions: read-all

name: update-cache
jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: cache mise
        uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2.1.1
        with:
          experimental: true
          cache: true
